### ISSUE TITLE
Suggestion: present/absent

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-nginx#1]
### Type of Report

Improvement

### Actual behaviour

Role can only do instalations.

### Expected behaviour

It would be awesome, if we can have a variable wtd_nginx_state.
This can be used in the package module then to be present/absent/updated.

There is one thing to consider. One has to check for the other tasks, which may be obsolete in case of "absent", so that they are not running. For example:

```
- name: Install package
  packages:
    state: "{{ wtd_nginx_state }}"

- name: Start service
  service:
    state: started
    enabled: yes
  when: wtd_nginx_state != absent
```
In this way, all roles can be used to install / remove the packages. For repo-roles this is already applied.
